engine:
  type: "in_memory"
network:
  address: "127.0.0.1:8080"
  max_connections: 100
  max_message_size: "4KB"
  idle_timeout: 5m
wal:
  flushing_batch_size: 100
  flushing_timeout: "10ms"
  max_segment_size: "10MB"
  dir_path: "data/wal"
logging:
  level: "debug"
  output: "log/output.log"